# Run many verifiers on metamath files.
# Only one verifier is necessary, but using multiple verifiers counters
# the risk that a verifier might have a defect in its implementation.
# With 4 verifiers, all 4 would have to have a defect involving an
# invalid theorem # for that invalid theorem to be accepted as valid.
# This is unlikely, because the verifiers are written by different people
# in different languages.  This can be considered extreme peer review, where
# every reviewer is separately checking each step.
# Some of these verifiers also check for style,
# so using multiple verifiers can also detect many different style problems.
#
# Note that one of the checks is scripts/verify.
#
# We report an error if the list of "discouraged" results is unexpected;
# this makes it easy to detect changes (which can then be specially reviewed).
# To regenerate the "discouraged" file, you can run scripts/gen-discouraged
#
# We typically rewrap the file using scripts/rewrap.
#
language: rust
git:
  depth: 3
sudo: false
cache:
  cargo: true # Cache Rust source/executables (takes time to get and recompile)
  timeout: 3600 # Cache for 1 hour (unit is seconds)
before_install:
  - gcc --version
  - g++ --version
install:
  # Download, build, and install what we need.
  # NOTE: We install programs in $HOME/bin, so ensure that's on the PATH
  # (usually it is on any non-Windows system).
  # Get metamath C program and supporting files (to validate against them)
  - scripts/download-metamath
  # Build/install metamath, a C verifier (and more) by Norm Megill.
  - scripts/build-metamath
  # Get mmj2, a Java verifier (and more) by Mel O'Cat and Mario Carneiro
  - wget -N -q http://us.metamath.org/ocat/mmj2/mmj2jar.zip
  - unzip -q mmj2jar.zip
  - jdk_switcher use oraclejdk8
  # Install smetamath-rs (smm3), a Rust verifier by Stefan O'Rear
  # See: https://github.com/sorear/smetamath-rs
  - "[ -x  ~/.cargo/bin/smetamath ] || cargo install smetamath --vers 3.0.0"
  # Get and compile checkmm, a C++ verifier by Eric Schmidt
  - wget -N -q http://us.metamath.org/downloads/checkmm.cpp
  - g++ -O2 -o checkmm checkmm.cpp
script:
  - scripts/verify --date_skip --extra 'write bibliography mmbiblio.html' set.mm
  - scripts/verify iset.mm
  # Verify and also also generate 'discouraged.new':
  - scripts/verify-mmj2 --extra 'RunMacro,showDiscouraged,discouraged.new' set.mm
  - echo 'Checking discouraged file:' && diff -U 0 discouraged discouraged.new
  - scripts/verify-mmj2 iset.mm
  - ~/.cargo/bin/smetamath --verify --split --jobs 4 --timing ./set.mm 2>&1 | tee smm.log && [ `egrep '(:Error:|:Warning:)' < smm.log; echo $?` -eq 1 ]
  - ~/.cargo/bin/smetamath --verify --split --jobs 4 --timing ./iset.mm 2>&1 | tee smm.log && [ `egrep '(:Error:|:Warning:)' < smm.log; echo $?` -eq 1 ]
  - echo 'Looking for tabs (not allowed)...' && ! grep "$(printf '\t')" set.mm
  - echo 'Looking for tabs (not allowed)...' && ! grep "$(printf '\t')" iset.mm
  - ./checkmm set.mm
  - ./checkmm iset.mm
